import "./globals.css";

export const metadata = {
  title: "Katsuya Scarborough Tip Calculator",
  description: "Generated by Tony Park",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        {children}
        <p className="ml-40 mt-25">Created By Tony Park</p>
      </body>
    </html>
  );
}
