import "./globals.css";

export const metadata = {
  title: "Katsuya Tip Calculator",
  description: "Generated by Tony Park",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        {children}
<p className="mt-6 flex justify-between px-5 text-sm text-gray-500">
  <span>Created By Tony Park</span>
  <span>V 1.0.0</span>
</p>
      </body>
    </html>
  );
}
